version: "3.7"

x-log: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

x-env-general: &env-general
  TZ: ${TZ:-Europe/Moscow}

services:
  fluentd-collector:
    build: ./docker
    <<: *default
    hostname: fluentd-collector
    volumes:
      - buffer:/var/log/fluent/
    ports:
      # forward ports
      - "24224:24224"
      - "24224:24224/udp"
      # http check ports      
      - "8888:8888"
      # prometheus check ports
      - "24231:24231"
    security_opt:
      - no-new-privileges:true
    networks:
      - fluentd-collector

networks:
  fluentd-collector:

volumes:
  buffer: