version: "3.7"

x-log: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

services:
  fluentd-collector:
    build: ./docker
    restart: ${RESTART_POLICY-always}
    <<: *default
    hostname: fluentd-collector-${LOCATION:-prod}
    volumes:
      - buffer:/var/log/fluent/
      - ./config/fluent.conf:/fluentd/etc/fluent.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # forward ports
      - ${FORWARD_PORT_FLUENTD:-34224}:34224
      - ${FORWARD_PORT_FLUENTD:-34224}:34224/udp
      # http check ports
      - ${FORWARD_FLUENTD_MONITOR_HTTP:-8888}:8888
      # prometheus check ports
      - ${FORWARD_FLUENTD_MONITOR_PROM:-24231}:24231
    security_opt:
      - no-new-privileges:true
    networks:
      - fluentd-collector

networks:
  fluentd-collector:

volumes:
  buffer: